name: build
on: workflow_dispatch

#on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

jobs:
  build-a30:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup-toolchain
      run: |
        sudo apt-get install build-essential make cmake wget autogen autoconf automake -y
        wget -q https://github.com/steward-fu/website/releases/download/miyoo-a30/a30_toolchain-v1.0.tar.gz
        tar xzf a30_toolchain-v1.0.tar.gz -C /tmp/ ; sudo mkdir -p /opt ; sudo mv /tmp/a30 /opt/miyoo/
        export PATH=/opt/miyoo/bin/:$PATH
    - name: make cfg
      run: |
        make -f Makefile.a30 cfg ; cat config.log
    - name: make
      run: |
        make -f Makefile.a30 
    - name: output
      run: |
        cat config.log
