name: build
on: workflow_dispatch

#on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

jobs:
  build-a30:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup-toolchain
      run: |
        sudo apt-get install build-essential make cmake wget autogen autoconf automake build-essential -y
        wget -q https://github.com/steward-fu/website/releases/download/miyoo-a30/a30_toolchain-v1.0.tar.gz
        tar xzf a30_toolchain-v1.0.tar.gz -C /opt/ 
        chmod +x /opt/a30/bin/*
        ls /opt /opt/a30/* 
        stat /opt/a30/bin/arm-a30-linux-gnueabihf-*
        /opt/a30/bin/arm-a30-linux-gnueabihf-gcc -v
    - name: make cfg
      run: |
        export PATH=/opt/a30/bin/:$PATH
        set -o pipefail
        if ! ( \
        make -f Makefile.a30 cfg  2>&1 \
        | tee /tmp/cfg.log \
        | grep ">>>" \
        ); then tail -n100 build.log && exit 1
        fi

    - name: Archive cfg logs
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: /tmp/cfg.log

    - name: make
      run: |
        make -f Makefile.a30 
    - name: output
      run: |
        cat config.log
